package dobryagin_shagiev;// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.Assert.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class AuthorizationSuccessTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void authorizationSuccess() throws InterruptedException {
    // Test name: authorizationSuccess
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://pikabu.ru/");
    // 2 | setWindowSize | 1536x864 | 
    auth();
    // 7 | assertText | /html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[2]/div[1]/a
    assertEquals(driver.findElement(By.xpath("//div[@class='user__info-item']//a[contains(@class, 'user__nick')]")).getText(), "cenec51975");
  }

  @Test
  public void emotionsTest() throws InterruptedException {
    // Test name: emotionsTest
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("https://pikabu.ru/");
    auth();
    // 2 | setWindowSize | 1536x864 |
    driver.manage().window().setSize(new Dimension(1536, 864));
    // 3 | runScript | window.scrollTo(0,255.1999969482422) |
    js.executeScript("window.scrollTo(0,255.1999969482422)");
    // 4 | click | //article[contains(@class, 'story')]//div[contains(@class, 'story__emotions')] |
    driver.findElement(By.xpath("//article[contains(@class, \'story\')]//div[contains(@class, \'story__emotions\')]")).click();
    // 5 | storeText | //div[contains(@class, 'emotions__popup')]//div[contains(@class, 'emotions__popup-item')][2]//div[contains(@class, 'emotions__popup-counter')]/span | count
    vars.put("count", driver.findElement(By.xpath("//div[contains(@class, \'emotions__popup\')]//div[contains(@class, \'emotions__popup-item\')][2]//div[contains(@class, \'emotions__popup-counter\')]/span")).getText());
    // 6 | echo | ${count} |
    System.out.println(vars.get("count").toString());
  }

  @Test
  public void reactionPlusOnPost() throws InterruptedException {
    // Test name: reactionPlusOnPost
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("https://pikabu.ru/");
    auth();
    // 2 | setWindowSize | 1536x864 |
    driver.manage().window().setSize(new Dimension(1536, 864));
    // 3 | storeText | xpath=//article/div/div/div/div[2] | countOfPlus
    vars.put("countOfPlus", driver.findElement(By.xpath("//article[@class='story']//div[contains(@class, 'story__rating-count')]")).getText());
    // 4 | echo | ${countOfPlus} |
    System.out.println(vars.get("countOfPlus").toString());
    // 5 | click | xpath=//article/div/div/div/div |
    driver.findElement(By.xpath("//article[@class='story']//div[contains(@class, 'story__rating-up')]")).click();
    // 6 | executeScript | return Number(${countOfPlus}) + 1 | newCountOfPlus
    vars.put("newCountOfPlus", js.executeScript("return Number(arguments[0]) + 1", vars.get("countOfPlus")));
    Thread.sleep(1000);
    var hhh = driver.findElement(By.xpath("//article[@class='story']//div[contains(@class, 'story__rating-count')]")).getText();
    // 7 | assertText | xpath=//article/div/div/div/div[2] | ${newCountOfPlus}
    Thread.sleep(1000);
    assertEquals(hhh, vars.get("newCountOfPlus").toString());
  }

  @Test
  public void reactions() throws InterruptedException {
    // Test name: Reactions
    // Step # | name | target | value
    // 1 | open | https://pikabu.ru |
    driver.get("https://pikabu.ru");
    auth();
    // 2 | click | //article[contains(@class, 'story')]//div[contains(@class, 'story__emotions')] |
    driver.findElement(By.xpath("//article[contains(@class, \'story\')]//div[contains(@class, \'story__emotions\')]")).click();
    Thread.sleep(1000);
    // 3 | storeText | //div[contains(@class, 'emotions__popup')]//div[contains(@class, 'emotions__popup-item')][2]//div[contains(@class, 'emotions__popup-counter')]/span | reactionsCount
    vars.put("reactionsCount", driver.findElement(By.xpath("//div[contains(@class, \'emotions__popup\')]//div[contains(@class, \'emotions__popup-item\')][2]//div[contains(@class, \'emotions__popup-counter\')]/span")).getText());
    // 5 | executeScript | return Number(${reactionsCount})+1; | reactionsCount
    vars.put("reactionsCount", js.executeScript("return Number(arguments[0])+1;", vars.get("reactionsCount")));
    driver.findElement(By.xpath("//div[contains(@class, \'emotions__popup\')]//div[contains(@class, \'emotions__popup-item\')][2]//div[contains(@class, \'emotions__popup-icon\')]")).click();
    // 6 | assertText | //div[contains(@class, 'emotions__popup')]//div[contains(@class, 'emotions__popup-item')][2]//div[contains(@class, 'emotions__popup-counter')]/span | ${reactionsCount}
    assertEquals(driver.findElement(By.xpath("//div[contains(@class, \'emotions__popup\')]//div[contains(@class, \'emotions__popup-item\')][2]//div[contains(@class, \'emotions__popup-counter\')]/span")).getText(), vars.get("reactionsCount").toString());
  }

  void auth() throws InterruptedException {
    driver.findElement(By.xpath("//*[@id=\"signin-form\"]/div[1]/div/div/input")).click();
    // 4 | type | //*[@id="signin-form"]/div[1]/div/div/input | cenec51975
    driver.findElement(By.xpath("//*[@id=\"signin-form\"]/div[1]/div/div/input")).sendKeys("cenec51975");
    // 5 | type | //*[@id="signin-form"]/div[2]/div/div/input | 123456ыумут
    driver.findElement(By.xpath("//*[@id=\"signin-form\"]/div[2]/div/div/input")).sendKeys("123456ыумут");
    // 6 | click | //*[@id="signin-form"]/div[7]/button |
    driver.findElement(By.xpath("//*[@id=\"signin-form\"]/div[7]/button")).click();
    Thread.sleep(12000);
  }

  @Test
  public void subscribe() throws InterruptedException {
    // Test name: subscribe
    // Step # | name | target | value
    // 1 | open | /communities |
    driver.get("https://pikabu.ru/");
    auth();
    driver.get("https://pikabu.ru/communities");
    // 2 | setWindowSize | 1536x864 |
    driver.manage().window().setSize(new Dimension(1536, 864));
    // 3 | click | css=.community:nth-child(1) button:nth-child(1) |
    driver.findElement(By.cssSelector(".community:nth-child(1) button:nth-child(1)")).click();
    // 4 | click |
    driver.findElement(By.xpath("//*[@id=\"menu-subs\"]/a")).click();
    Thread.sleep(2000);
    // 5 | assertText | css=.subscription-item__text:nth-child(2) | Будь как дома, Путник
    assertEquals(driver.findElement(By.cssSelector(".subscription-item__text:nth-child(2)")).getText(), "Как это сделано");
  }
}
