package dobryagin_shagiev;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class DarkThemeTest {
  private WebDriver driver;

  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void darkTheme() throws InterruptedException {
    driver.get("http://pikabu.ru");

    List<WebElement> elements = driver.findElements(By.xpath("//html[@data-theme-dark='true']"));
    assertTrue(elements.isEmpty());

    driver.findElement(By.xpath("//div[@class='theme-picker']")).click();
    Thread.sleep(1000);
    driver.findElement(By.xpath("//div[@class='theme-picker__dark']/*/span")).click();

    elements = driver.findElements(By.xpath("//html[@data-theme-dark='true']"));
    assertFalse(elements.isEmpty());
  }
}
