package dobryagin_shagiev;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EmotionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void emotionsTest() {
    // Test name: emotionsTest
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://pikabu.ru/");
    // 2 | setWindowSize | 1536x864 | 
    driver.manage().window().setSize(new Dimension(1536, 864));
    // 3 | runScript | window.scrollTo(0,255.1999969482422) | 
    js.executeScript("window.scrollTo(0,255.1999969482422)");
    // 4 | click | //article[contains(@class, 'story')]//div[contains(@class, 'story__emotions')] | 
    driver.findElement(By.xpath("//article[contains(@class, \'story\')]//div[contains(@class, \'story__emotions\')]")).click();
    // 5 | storeText | //div[contains(@class, 'emotions__popup')]//div[contains(@class, 'emotions__popup-item')][2]//div[contains(@class, 'emotions__popup-counter')]/span | count
    vars.put("count", driver.findElement(By.xpath("//div[contains(@class, \'emotions__popup\')]//div[contains(@class, \'emotions__popup-item\')][2]//div[contains(@class, \'emotions__popup-counter\')]/span")).getText());
    // 6 | echo | ${count} | 
    System.out.println(vars.get("count").toString());
  }
}
