package dobryagin_shagiev;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class MoveUpTest {
  private WebDriver driver;

  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void moveUp() throws InterruptedException {
    driver.get("http://pikabu.ru");
    List<WebElement> elements = driver.findElements(By.xpath("//header[contains(@class, 'header_collapsed')]"));
    assertEquals(0, elements.size());

    js.executeScript("window.scrollTo(0,10000)");
    Thread.sleep(1000);
    elements = driver.findElements(By.xpath("//header[contains(@class, 'header_collapsed')]"));
    assertEquals(1, elements.size());

    driver.findElement(By.xpath("//div[contains(@class, 'scroll-up-button')]")).click();
    Thread.sleep(1000);
    elements = driver.findElements(By.xpath("//header[contains(@class, 'header_collapsed')]"));
    assertEquals(0, elements.size());

  }
}
