package dobryagin_shagiev;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class ReactionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void reactions() {
    // Test name: Reactions
    // Step # | name | target | value
    // 1 | open | https://pikabu.ru | 
    driver.get("https://pikabu.ru");
    // 2 | click | //article[contains(@class, 'story')]//div[contains(@class, 'story__emotions')] | 
    driver.findElement(By.xpath("//article[contains(@class, \'story\')]//div[contains(@class, \'story__emotions\')]")).click();
    // 3 | storeText | //div[contains(@class, 'emotions__popup')]//div[contains(@class, 'emotions__popup-item')][2]//div[contains(@class, 'emotions__popup-counter')]/span | reactionsCount
    vars.put("reactionsCount", driver.findElement(By.xpath("//div[contains(@class, \'emotions__popup\')]//div[contains(@class, \'emotions__popup-item\')][2]//div[contains(@class, \'emotions__popup-counter\')]/span")).getText());
    // 4 | click | //div[contains(@class, 'emotions__popup')]//div[contains(@class, 'emotions__popup-item')][2]//div[contains(@class, 'emotions__popup-icon')] | reactionsCount
    driver.findElement(By.xpath("//div[contains(@class, \'emotions__popup\')]//div[contains(@class, \'emotions__popup-item\')][2]//div[contains(@class, \'emotions__popup-icon\')]")).click();
    // 5 | executeScript | return Number(${reactionsCount})+1; | reactionsCount
    vars.put("reactionsCount", js.executeScript("return Number(arguments[0])+1;", vars.get("reactionsCount")));
    // 6 | assertText | //div[contains(@class, 'emotions__popup')]//div[contains(@class, 'emotions__popup-item')][2]//div[contains(@class, 'emotions__popup-counter')]/span | ${reactionsCount}
    assertThat(driver.findElement(By.xpath("//div[contains(@class, \'emotions__popup\')]//div[contains(@class, \'emotions__popup-item\')][2]//div[contains(@class, \'emotions__popup-counter\')]/span")).getText(), is("vars.get(\"reactionsCount\").toString()"));
  }
}
