package dobryagin_shagiev;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;

  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void search() {
    driver.get("http://pikabu.ru");
    driver.findElement(By.xpath("//div[contains(@class, 'header-right-menu__search')]")).click();
    driver.findElement(By.xpath("//div[contains(@class, 'header-right-menu__search')]//form//input[@placeholder='Поиск']")).sendKeys("OPA");
    driver.findElement(By.xpath("//div[contains(@class, 'header-right-menu__search')]//form//button[@type='submit']")).click();
    driver.findElement(By.xpath("//div[contains(@class, 'header-right-menu__search')]//form//button[@type='submit']")).click();
    vars.put("uuurl", js.executeScript("return document.URL"));
    assertEquals(vars.get("uuurl").toString(), "https://pikabu.ru/search?q=OPA&st=3");
  }
}
