package dobryagin_shagiev;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class SubscribeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void subscribe() {
    // Test name: subscribe
    // Step # | name | target | value
    // 1 | open | /communities | 
    driver.get("https://pikabu.ru/communities");
    // 2 | setWindowSize | 1536x864 | 
    driver.manage().window().setSize(new Dimension(1536, 864));
    // 3 | click | css=.community:nth-child(1) button:nth-child(1) | 
    driver.findElement(By.cssSelector(".community:nth-child(1) button:nth-child(1)")).click();
    // 4 | click | linkText=Подписки | 
    driver.findElement(By.linkText("Подписки")).click();
    // 5 | assertText | css=.subscription-item__text:nth-child(2) | Будь как дома, Путник
    assertThat(driver.findElement(By.cssSelector(".subscription-item__text:nth-child(2)")).getText(), is("Будь как дома, Путник"));
  }
}
